trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'acr-service-connection'
  imageRepository: 'todo-service'
  dockerfilePath: '**/Dockerfile'
  tag: 'latest'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: $(vmImageName)
      steps:
      - script: wget https://dist.ballerina.io/downloads/1.2.7/ballerina-1.2.7.zip
      - script: unzip -d /opt ballerina-1.2.7.zip
      - script: /opt/ballerina-1.2.7/bin/ballerina build todo_service.bal
      - script: mv docker/Dockerfile .
      - task: Docker@2
        displayName: Build and push the image to Azure container registry
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: $(dockerfilePath)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(tag)
      
      